### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by CrisBRM** [bohoomil/fontconfig-ultimate#107]
Running eselect fontconfig list no longer lists ````52-ultimate.conf```` but rather, ````52-infinality.conf````. It is listed under lcdfilter and infinality. Am I doing something wrong, or is this intentional?

**Comment by bohoomil** [comment]
You should ask for support on your distro's Forums: I don't support the old style fontconfig-infinality.

**Comment by CrisBRM** [comment]
It is intentional. Thanks and sorry for wasting your time.
Great project!
