### ISSUE TITLE
Input font package

### ISSUE THREAD

**Issue by 4e6** [bohoomil/fontconfig-ultimate#113]
Request for Input font http://input.fontbureau.com/
There is also aur package https://aur.archlinux.org/packages/ttf-input/

Initially discussed on g+, where I described the issue with hinting https://plus.google.com/u/0/+DmitryBushev/posts/Bq8Jzf7f5vQ

**Comment by bohoomil** [comment]
Unfortunately, their [license](http://input.fontbureau.com/license/) states it clearly:

> NO REDISTRIBUTION. You may not distribute the Font Software to third parties for the purposes of permitting the display of the Font Software or allowing or facilitating redistribution of the Font Software irrespective of the terms of the redistribution. For the purposes of clarity you are not permitted to embed the Font Software or otherwise bundle the Font Software with another file. All such uses require the purchase of a special license.

BTW, I wanted to add the family to the repo myself quite a time ago... ;-)

**Comment by 4e6** [comment]
That's sad. For the record, I came up with fontconfig that disables `autohint`, that solved my issue (letter 'm' on screenshot) 4e6/dotfiles@b4329f385c325f7ebabd9a7da46df9f117c099fa

![2015-10-10-084642_2560x1440_scrot-animation](https://cloud.githubusercontent.com/assets/357683/10416006/c4d3e484-700b-11e5-95d8-caaac742856d.gif)

**Comment by bohoomil** [comment]
Changing hinting to `none` isn't a good idea as it affects all the fonts globally. Instead, either modify `90-tt-input.conf` or disable it altogether. This should fix issues with the particular font while leaving others unaffected.

**Comment by 4e6** [comment]
I'm a bit confused, I thought that I left autohinting enabled globally with `Xft.hintstyle: hintfull` and disabled autohinting for Input font with `90-tt-input.conf`
```
<edit name="autohint" mode="assign">
  <bool>false</bool>
</edit>
```

Can you clarify are the following statements correct? 
+ Xresources option `Xft.hintstyle` (how aggressively apply hinting) can be applied to both bytecode and autohint hinting
+ By default, autohinting is used if it is not explicitly disabled for particular font.

**Comment by bohoomil** [comment]
Oh... I'm sorry -- I completely misread the [diff](https://github.com/bohoomil/fontconfig-ultimate/issues/113#issuecomment-147172405). Yes, everything is perfectly correct there, hinting is set to `full` and that's what I meant. Sorry again: my bad.
