### ISSUE TITLE
Noto in community

### ISSUE THREAD

**Issue by jristz** [bohoomil/fontconfig-ultimate#115]
Resently noto was added to community and it install in  they oun folder usr/share/fonts/noto

considering that you conflict this with any copy is need a new conflict, also the community use a different package (noto-fonts, noto-fonts-cjk, noto-fonts-emoji), it will be good if you coppy the name cheming (ttf-noto-fonts-sans, ttf-noto-fonts-cjk, ttf-noto-fonts-emoji...) to prevent user to isinterpret the font with the propper encodings.

Als my superbundle ttf-chromeosextra-font was updated and for some reason now can be installed alongside your font, even the ones who add the same fonts (ttf-chromeosextra.font and arimo, courino & tinos, why?

**Comment by bohoomil** [comment]
Thanks for the info and sorry for a late response.

I'm preparing new Noto packages which should resolve the issues.

**Comment by bohoomil** [comment]
The packages have been upgraded. Please, read [this post](https://plus.google.com/+bohoomil-infinality-bundle/posts/SR1K61viFm6) for details, including upgrade instructions.

**Comment by jristz** [comment]
'''ttf-noto-serif-multilang-ib: need ttf-noto-serif-ib'''
I can safely '''pacman -Rdd ttf-noto-serif-multilang-ib''' or you gonna do somekind of provides and replaces??

**Comment by bohoomil** [comment]
Did you read the upgrade notes [here](https://plus.google.com/+bohoomil-infinality-bundle/posts/SR1K61viFm6)? ;-) Yes, you need to remove two packages manually.
