### ISSUE TITLE
[Arch Linux] infinality-bundle-fonts-extra can't be installed

### ISSUE THREAD

**Issue by rdoursenaud** [bohoomil/fontconfig-ultimate#117]
Two conflicting packages are part of the group defeating the purpose of the group.

```
resolving dependencies...
looking for conflicting packages...
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: otf-alegreya-ibx and ttf-alegreya-ibx are in conflict
```

**Comment by bohoomil** [comment]
It has been explained dozens of times: you neither want to or need to install the same family in two contradicting formats. Install either a TT version or the OTF, not both.

**Comment by DoctorJellyface** [comment]
As it's explained on the [Arch Wiki](https://wiki.archlinux.org/index.php/Infinality#More_fonts), you do **not** want to install the whole bundle, just install `ib-fonts-meta-base` and `ib-fonts-meta-extended`, maybe you'll want even `ib-fonts-meta-extended-lt`, dunno if that installs automatically, it did for me I think.

**Comment by rdoursenaud** [comment]
OK, my bad. Didn't RTFM enough. Sorry for the noise.

But the group is still misleading since they are designed to be installed all at once…

Anyway, thanks for your great job!
