### ISSUE TITLE
In release 2015-11-30, INFINALITY_FT envvar not exported

### ISSUE THREAD

**Issue by goddesse** [bohoomil/fontconfig-ultimate#123]
I think this should be preceded with export to be properly read by the new code as there's still a getenv to read it, right?

**Comment by CrisBRM** [comment]
I'm using the git build (today's) and running ```grep INFINALITY <(env)``` works for me.

**Comment by goddesse** [comment]
Thank you, I'm actually using ZSH.

**Comment by bohoomil** [comment]
Yes, I didn't include the right file in the repo and in the package. Fixing it.
