### ISSUE TITLE
WebKit browsers (Chromium, Opera) won't use freetype2 run-time settings with the new Infinality patch

### ISSUE THREAD

**Issue by bohoomil** [bohoomil/fontconfig-ultimate#124]
The problem was originally reported by Perfect Gentleman and [SpaceCadet](https://bbs.archlinux.org/viewtopic.php?pid=1582977#p1582977) on Arch Linux forum:

> I'm experiencing the same with Google Chrome. On web pages it seems to ignore my infinality settings completely. Strangely enough, the differences *are* visible in the Chrome UI itself (menus, bookmarks, tab titles).
>
> I tested it first by trying out the various INFINALITY_FT presets, and later by setting the variables manually and explicitly setting INFINALITY_FT_BRIGHTNESS="-100" to make my fonts super bold [edited to add: just so I would notice whether it changes anything, not because I like my fonts that way], and none of it made any change to how the fonts were rendered on web pages in Chrome, while on Firefox it made a very noticeable difference.

I reproduced the problem and here are the screenshots:

* Chromium + `freetype2-iu`, rev.2.6.2 with the new Infinality patch:

![chromium_ultimate3](https://cloud.githubusercontent.com/assets/421230/11519700/8ffd87ba-989c-11e5-962c-6b310292e2d9.png)

* Chromium + `freetype2-iu`, rev.2.6.2 with the old Infinality patch:

![chromium_testing_old_inf_patch](https://cloud.githubusercontent.com/assets/421230/11519728/c0fccfce-989c-11e5-8396-0c155dfefd51.png)

**Comment by goddesse** [comment]
@bohoomil and @mviikki16. Looking at the SKIA code, it doesn't call the plain FT_Init_FreeType function, but rather the custom FT_New_Library and then FT_Add_Default_Modules. I wonder if the ennvars were initialized there too with ftinf_env() WebKit would start working with Infinality settings again.

**Comment by mviikki16** [comment]
Indeed, <b>ftinf_env must be called</b> for Infinality to be active, a call at the end of FT_New_Library should solve the issue. It  is also possible to update ftinf_env to skip multiple initialisations (in cases where it gets called more than once) but beside the little wasted computation that's far less of a problem than when no call to it is done at all.

**Comment by mviikki16** [comment]
Here's a small and quick update to latest patch version (inf_patch_all.txt) to add the reading of settings also from  FT_New_Library and skip multiple calls of ftinf_env. 

[inf_upd.txt](https://github.com/bohoomil/fontconfig-ultimate/files/50973/inf_upd.txt)

**Comment by mviikki16** [comment]
and this is a bit of cleanup for redundant code.

[inf_clnup.txt](https://github.com/bohoomil/fontconfig-ultimate/files/51595/inf_clnup.txt)

**Comment by perfect7gentleman** [comment]
how should these patches be applied ?

**Comment by bohoomil** [comment]
@mviikki16 Thank you very much!

@perfect7gentleman I'll prepare the patches soon, please wait a little bit.
