### ISSUE TITLE
Some fonts are strangely cut off

### ISSUE THREAD

**Issue by Swatinem** [bohoomil/fontconfig-ultimate#126]
I’m not really sure if this is the right place to report such issues. So sorry in advance if that is the case.

Anyway. Since I updated my arch to `freetype2-infinality-ultimate (2.6.1-3 -> 2.6.2-3)`, some of my fonts in firefox, including the UI fonts are messed up quite bad, see the attached screenshot.

I also updated my firefox, so that might actually be the cause of the problem, since I haven’t seen this in other programs. `firefox-nightly (45.0a1.20151126-1 -> 45.0a1.20151202-1)`

![bildschirmfoto vom 2015-12-02 15-20-35](https://cloud.githubusercontent.com/assets/580492/11533314/42119eca-9909-11e5-9972-5d2d4d7389cc.png)

**Comment by bohoomil** [comment]
I cannot confirm this:

![firefox-fira](https://cloud.githubusercontent.com/assets/421230/11544010/f3e4a166-993f-11e5-95ae-5bc71978e1ed.png)

Did you try rebuilding the font cache (`fc-cache -fv`)?

**Comment by Swatinem** [comment]
yes, I did that. I will try with a different firefox version soon to see if that was the problem or not. But strangely, I only have this problem with some fonts on some pages. For example github looks perfect. Its just annoying that the UI is also screwed up in that way.

**Comment by bohoomil** [comment]
I checked out firefox-nightly 45.0a1.20151105-1 and it's working just fine. Which rendering style are you using? Any of the built-in or a custom one?

**Comment by Swatinem** [comment]
Sorry for the long delay.
As far as I can remember, I have only set the hinting somewhere in `/etc/fonts` but I can’t remember as that was more than 2 years ago.

I have tried downgrading the freetype lib and it fixed the main problem of cut-off fonts, but other problems did remain.

I also noticed that here on github the hinting is wrong in some cases, see the screenshot:
![bildschirmfoto vom 2015-12-20 11-51-13](https://cloud.githubusercontent.com/assets/580492/11917655/8f4cccc2-a710-11e5-931e-6a7e8f632c29.png)

So maybe it is some kind of messed up config somewhere. Can you point me to some guide how I can reset everything back to default?

**Comment by Swatinem** [comment]
Seems like this really was a problem with firefox, or more specifically me using an unsupported/unstable setting.

Here is the bug, just for reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1208644

sorry for the inconvenience, and thanks for the help :-)
