### ISSUE TITLE
ttf-fira-sans-ibx does not provide ttf-fira-sans

### ISSUE THREAD

**Issue by pedronariyoshi** [bohoomil/fontconfig-ultimate#129]
Hi,
I'm not sure if this is the right to post this, but I'm installing a package that requires ttf-fira-sans, but while the PKGBUILD states that ttf-fira-sans-ibx conflicts with ttf-fira-sans, it does not state that it also provides ttf-fira-sans. I was able to fix my problem ad-hoc, but just wanted to report this here.

**Comment by bohoomil** [comment]
Hi,

Does `ttf-fira-sans-ibx` have to provide `ttf-fira-sans`? I mean, is `ttf-fira-sans` a dependency for another package like, say, `ttf-dejavu` is? The `provide` array is used mostly in certain cases when package `b` is an equivalent of package `a` which in turn should be substituted with `b` for one reason or another (e.g. `a` is a dependency, `b` provides a better quality font than `a`, etc.). Other than that, `conflicts` is enough to prevent the double installation of a physically similar package (in this case, `ttf-fira-sans-ibx` provides additional `fontconfig` configuration files to ensure the rendering of the family is correct).

**Comment by pedronariyoshi** [comment]
The package is beamer-theme-git, which is on AUR. The theme requires 
ttf-fira-sans to work. I don't know if the package is doing anything 
non-standard, but to "look right", it does need ttf-fira-sans to be 
installed.

I'm actually not sure what the default behavior in these cases should 
be. Should the theme package only require fonts as optional deps? Are 
there any risks of including "provides" in the PKGBUILD? I don't want 
to create a "dirty hack" just to solve a personal non-problem.

**Comment by bohoomil** [comment]
This is absolutely not a problem for me to add the line: I only wanted to explain my packaging strategy so that you can see some logic behind it. Actually your case is exactly what I was asking about. And sure, I'll rebuild the package soon.

**Comment by pedronariyoshi** [comment]
Thanks! (;
