### ISSUE TITLE
[Arch] infinality-bundle-fonts has conflicting depedencies

### ISSUE THREAD

**Issue by Mikaela** [bohoomil/fontconfig-ultimate#134]
```
:: There are 46 members in group infinality-bundle-fonts:
:: Repository infinality-bundle-fonts
   1) otf-heuristica-ib  2) otf-oswald-ib  3) otf-quintessential-ib
   4) otf-tex-gyre-ib  5) t1-bh-ib  6) t1-cursor-ib  7) t1-dejavu-ib
   8) t1-urw-fonts-cyr-ib  9) t1-urw-fonts-ib  10) ttf-bh-ib
   11) ttf-caladea-ib  12) ttf-cantoraone-ib  13) ttf-carlito-ib
   14) ttf-courier-prime-ib  15) ttf-ddc-uchen-ib  16) ttf-dejavu-ib
   17) ttf-droid-ib  18) ttf-droid-nonlatin-ib  19) ttf-faruma-ibx
   20) ttf-gelasio-ib  21) ttf-hack-ibx  22) ttf-heuristica-ib
   23) ttf-inknut-antiqua-ibx  24) ttf-liberastika-ib  25) ttf-liberation-ib
   26) ttf-lohit-assamese-ib  27) ttf-lohit-bengali-ib
   28) ttf-lohit-devanagari-ib  29) ttf-lohit-gujarati-ib
   30) ttf-lohit-gurmukhi-ib  31) ttf-lohit-kannada-ib
   32) ttf-lohit-malayalam-ib  33) ttf-lohit-marathi-ib
   34) ttf-lohit-nepali-ib  35) ttf-lohit-odia-ib  36) ttf-lohit-punjabi-ib
   37) ttf-lohit-tamil-ib  38) ttf-lohit-telugu-ib  39) ttf-merriweather-ib
   40) ttf-merriweather-sans-ib  41) ttf-monoid-ibx  42) ttf-noto-fonts-ib
   43) ttf-noto-fonts-nonlatin-ib  44) ttf-opensans-ib  45) ttf-symbola-ib
   46) ttf-ubuntu-font-family-ib

Enter a selection (default=all): 
resolving dependencies...
looking for conflicting packages...
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: t1-bh-ib and ttf-bh-ib are in conflict
```

If this is intended, where can I find instructions for installing the fonts selecting which of those I want?

**Comment by itzexor** [comment]
The docs are here http://bohoomil.com/doc/05-fonts/

**Comment by Mikaela** [comment]
It seems that this package group is not docunented on that page or has different name as CTRL+F is unable to find it.

**Comment by Mikaela** [comment]
> The infinality-bundle-fonts repository contains a comprehensive collection of free fonts gathered in the **ibfonts-meta-base, ibfonts-meta-extended and ibfonts-meta-extended-lt meta packages.**

Apparently I cannot read and pacman probably thought I wanted to install everything in the repo or something like that.

**Comment by rokups** [comment]
`infinality-bundle-fonts` contains both `t1-bh-ib` and `ttf-bh-ib`. The way i see it its a bug in group definition. Otherwise why define a package group that cant be installed.. This should be reopened.

**Comment by ghost** [comment]
When asked to enter a selection, I inputted this `1-8 10-14 16-20 22-45` to fix all of the conflicts. Kind of annoying but it doesn't really matter I guess since they're basically the same thing.

The arch wiki says only to install the font that you need.
