### ISSUE TITLE
[Arch] provide build instructions for packages

### ISSUE THREAD

**Issue by inglor** [bohoomil/fontconfig-ultimate#137]
Hello,

The project webpage has a [Documentation] page on which the Building and Installing instructions are not covered. The [building] url is not really referenced anywhere. Ultimately looking for the PKGBUILD as I couldn't find it in AUR.

Thanks

[Documentation]: http://bohoomil.com/doc/
[building]: http://bohoomil.com/doc/02-building/

**Comment by perfect7gentleman** [comment]
you can find them here, right in this repo

**Comment by bohoomil** [comment]
@inglor Please, check out the `pkgbuild` branch: you'll find each and every build script there.

**Comment by Arthur2e5** [comment]
Look for {cairo,freetype2,fontconfig}-infinality in AUR. These packages have switched to bohoomil's patches.

**Comment by inglor** [comment]
Thanks
