### ISSUE TITLE
crash with certain (buggy?) fonts

### ISSUE THREAD

**Issue by mviikki16** [bohoomil/fontconfig-ultimate#138]
Some fonts seem to be lacking the **style_name** property which causes a crash in **af_latin_compute_stem_width** function with infinality updates. 

This is fixed with the patch below (applied on top of a5952d3049ff880bb8eea94f045b32575e59b58f from master with merged infinality but it's small enough to work at any level).

However, there might be other unchecked uses of **strstr**, no time to investigate on them but I'll do it if I still see such crashes. In my case the problem occurred when browsing web-pages requiring affected fonts (perhaps this is a font problem to start with, but I had no time to identify which font(s) trigger it).   

[sigseg_strstr.txt](https://github.com/bohoomil/fontconfig-ultimate/files/140786/sigseg_strstr.txt)

**Comment by bohoomil** [comment]
Done. Thank you very much for the patch!
