### ISSUE TITLE
 fontconfig ultimate slows down programs startup

### ISSUE THREAD

**Issue by kokoko3k** [bohoomil/fontconfig-ultimate#139]
Sorry to not have submitted here in first place.
A detailed description of the issue is available here:
https://bbs.archlinux.org/viewtopic.php?id=209687

**Comment by kokoko3k** [comment]
Seems "upstream" git is affected too.
2.11.1 is fine 2.11.94 is not; and depsite the package i installed is named:
infinality-bundle/fontconfig-infinality-ultimate 2.11.1-30
it is indeed based on the 2.11.94 git version.

**Comment by cynecx** [comment]
Hey,

It seems that the commit which caused this issue has been reverted:
https://cgit.freedesktop.org/fontconfig/commit/?id=d179cbc2536af16cf0f4992e0a4b2d751437ee6c

So upstream git should be fixed.

**Comment by bohoomil** [comment]
I hope I will be able to update `fontconfig-iu` this weekend. Thanks for reporting and the link.
