### ISSUE TITLE
DejaVu Sans Mono with ripples

### ISSUE THREAD

**Issue by SammysHP** [bohoomil/fontconfig-ultimate#140]
Using underscores or other touching lines with DejaVu Sans Mono from ttf-dejavu-ib create small ripples on the connections, for example here: http://wttr.in/ (if you use DejaVu Sans Mono). I'm using the ms preset.

![20160312_124305](https://cloud.githubusercontent.com/assets/922874/13722765/07f08b2a-e850-11e5-8ecf-f1577b7a63ab.png)

**Comment by bohoomil** [comment]
Could you check this out with the updated libs? As far as I can tell, some fonts look this way and Infinality has nothing to do with it. (BTW, I don't have a clue why this might be happening.)

**Comment by SammysHP** [comment]
This is much better now, thanks!
![20160329_162057](https://cloud.githubusercontent.com/assets/922874/14111256/50dcbc14-f5ca-11e5-87ce-5372ad389e84.png)
