### ISSUE TITLE
Use pacman hooks

### ISSUE THREAD

**Issue by rumpelsepp** [bohoomil/fontconfig-ultimate#141]
Since pacman 5 supports hooks, all the package scripts can be simplified.

**Comment by bohoomil** [comment]
Thanks, I'll look into it.

**Comment by jristz** [comment]
https://github.com/andrewgregory/pachooks

that repo have many examples of hooks, including hooks/fc-cache.hook with an example on how font hook.

**Comment by rumpelsepp** [comment]
I guess the arch devs will provide such a font hook anyway. bohoomil might only remove the install scripts from the packages when the hook is there.

**Comment by jristz** [comment]
But boohomil install the fonts in a diferent directory than the default one, so then the fonts either should be moved to the default or ensure that the hook that finally land look for bohoo fonts directories.

**Comment by rumpelsepp** [comment]
Ahh. Got it. :-)

On April 3, 2016 11:14:45 PM GMT+02:00, " Pablo Lezaeta Reyes [pˈaβ̞lo lˌe̞θaˈeta rˈejɛ]" <notifications@github.com> wrote:
>But boohomil install the fonts in a diferent directory than the default
>one, so then the fonts either should be moved to the default or ensure
>that the hook that finally land look for bohoo fonts directories.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bohoomil/fontconfig-ultimate/issues/141#issuecomment-205056484

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bohoomil** [comment]
Thanks for the hints guys.

**Comment by bohoomil** [comment]
I added a hook to the new release of `fontconfig-iu` (see `/etc/pacman.d/hooks/`). As far as I can tell, it does the job as expected. Please, test it on your own and leave a comment in case you have a suggestion.

**Comment by rumpelsepp** [comment]
I am currently just on my mobile phone, will test it later. But there is one nit pick: packages should not contain files in /etc. Just use the higher priority directory in /usr . I cannot find it in the documentation ATM, but I will search it later today. The reason for that is, packagers but files in /usr, the admin can overwrite them locally in /etc.

**Comment by bohoomil** [comment]
@rumpelsepp -- thank you very much. My bad, I forgot about it. The update is already in the repo with the hook installing to `/usr/share/libalpm/hooks` as `90-fc-cache-ib.hook`.

**Comment by rumpelsepp** [comment]
:+1: Seems to work for me. Thanks! :)
