### ISSUE TITLE
Add Cairo patch to make FT_LCD_FILTER_DEFAULT the actual default lcdfilter

### ISSUE THREAD

**Issue by CrisBRM** [bohoomil/fontconfig-ultimate#143]
https://github.com/CrisBRM/fontconfig-ultimate/blob/master/cairo/cairo-lcdfilter-make-default-default.patch

FT_LCD_FILTER_LEGACY is completely useless and introduces excessive colour fringes.

**Comment by bohoomil** [comment]
Thanks -- done.
