### ISSUE TITLE
Xorg not working

### ISSUE THREAD

**Issue by pit65** [bohoomil/fontconfig-ultimate#146]
Slackware current.

After aplying patchset I have got 32MB Xorg.0.log with this:

959.190] (II) GetModeLine - scrn: 0 clock: 135000
[   959.190] (II) GetModeLine - hdsp: 1280 hbeg: 1328 hend: 1440 httl: 1688
[   959.190] (II)               vdsp: 1024 vbeg: 1025 vend: 1028 vttl: 1066 flags: 5

Xorg not work.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by pit65** [comment]
Only freetype patchset.

**Comment by onodera-punpun** [comment]
W-what did you do to my github timeline: https://sr.ht/YalA.png

**Comment by pit65** [comment]
Sory I'm not familiar with github, but I delated may excess comments.

**Comment by bohoomil** [comment]
Sorry, I have nothing to do with Xorg, especially on Slackware. Please, ask your community for assistance.
