### ISSUE TITLE
ttf-fira-mono-ibx does not provide ttf-fira-mono

### ISSUE THREAD

**Issue by pedronariyoshi** [bohoomil/fontconfig-ultimate#147]
Hi Bohoomil,
This issue is similar to #129 , but for fira-mono instead. Could you change that on the repo?
Thank you (;

**Comment by bohoomil** [comment]
Thanks for reporting. I will update the packages once I'm back in Linux. ;-)

**Comment by bohoomil** [comment]
Both Fira families were upgraded and the missing feature was added.
