### ISSUE TITLE
conflict

### ISSUE THREAD

**Issue by jristz** [bohoomil/fontconfig-ultimate#150]
error: can't finish (file conflict)
ttf-libre-bodoni-ibx: /etc/fonts/conf.avail/45-libre-bodoni.conf exist
ttf-libre-bodoni-ibx: /etc/fonts/conf.d/45-libre-bodoni.conf exist
errors hapend, no continue
$ pacman -Qo /etc/fonts/conf.d/45-libre-bodoni.conf
/etc/fonts/conf.d/45-libre-bodoni.conf owned by otf-libre-bodoni-ibx 1.001-1
$ pacman -Qo /etc/fonts/conf.avail/45-libre-bodoni.conf
/etc/fonts/conf.avail/45-libre-bodoni.conf owned by otf-libre-bodoni-ibx 1.001-1

aparently install otf-libre-bodoni-ibx and then install-replace with the ttf variant ended in a file conflict,
help? they aren't supposed to provide one each other?

**Comment by bohoomil** [comment]
Because I screw the `conflicts` array. I'll update the packages. Thanks for reporting.
