### ISSUE TITLE
custom_postjob() in fc-presets

### ISSUE THREAD

**Issue by BubuXP** [bohoomil/fontconfig-ultimate#151]
I'm trying to package infinality-ultimate for Debian. I don't understand well code in general, but while checking it I found the following in fc-presets.

row 196 is
`        ln -s ../conf.avail.infinality/35-repl-custom.conf . 2>/dev/null`
shouldn't it be
`        ln -s $presets_dir/35-repl-custom.conf $config_dir 2>/dev/null`

and also row 192
` if [[ $check_current == *combi* ]] && [[ -f ./35-repl-custom.conf ]]; then`
shouldn't it be
` if [[ $check_current == *combi* ]] && [[ -f $config_dir/35-repl-custom.conf ]]; then`

**Comment by bohoomil** [comment]
Yes, there should be variables. Thanks for taking your time and tracking it down.

**Comment by BubuXP** [comment]
Very fast response, thank you.
But maybe you forgot something. It's now:
`ln -s $presets_dir/35-repl-custom.conf . 2>/dev/null`
but it should be:
`ln -s $presets_dir/35-repl-custom.conf $config_dir 2>/dev/null`
right?

**Comment by bohoomil** [comment]
Probably like this would be better:

`ln -s $presets_dir/35-repl-custom.conf $config_dir/35-repl-custom.conf 2>/dev/null`

**Comment by BubuXP** [comment]
I didn't answer because it was ok, but it works even without repeating the file name, as the link will retain the same name.

I found another row (180) with a similar syntax. It's:
`ln -sf $target .`
better:
`ln -sf $target $config_dir`

**Comment by bohoomil** [comment]
Thanks for the feedback. I'm not on Linux right now but as soon as I'm, I'll fix the line.
