### ISSUE TITLE
please provide libfreetype

### ISSUE THREAD

**Issue by SolarAquarion** [bohoomil/fontconfig-ultimate#158]
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/libbluray&id=b3a528f394d18a39aea4893a0f7098589b15b0d5

**Comment by FadeMind** [comment]
@bohoomil :+1:  for this.

**Comment by bohoomil** [comment]
Sorry, I don't really get it. Which package should actually provide what (the title says `libfreetype`, the link points to `libbluray`)? What's the rationale behind it?

**Comment by jristz** [comment]
freetype2-infinality should provide, replace and chill for freetype2, that
because now libbluray depend explicity on freetype2.

**Comment by bohoomil** [comment]
Oh, I see. Thanks a lot for clarification. I'll prepare a new release soon.

**Comment by jristz** [comment]
Just to add more to this: freetype2-infinality provides freetype2 just fine, it's libbluray depending on libfreetype.so=6.64 which freetype2 provides, but freetype2-infinality doesn't (at least not according to it's PKGBUILD).

**Comment by bohoomil** [comment]
The stock `freetype2` PKGBUILD contains `provides=('libfreetype.so')` which I guess is exactly what should be in ours as well.
