### ISSUE TITLE
Drop ttf-droid-ib from ibfonts-meta-extended-lt

### ISSUE THREAD

**Issue by julroy67** [bohoomil/fontconfig-ultimate#163]
As noted in noto-fonts FAQ, droid font will no longer be updated and noto fonts are already a better replacement. How about removing this package from ibfonts-meta-extended-lt ?

> How does Noto relate to Droid?
> 
> Google’s Droid fonts have been superseded by Noto. Noto began as Droid, and all updates are now made to the Noto fonts. Today, Noto gives better support to all languages covered by Droid, with more characters and fewer bugs, and it covers many more languages. Both Android and ChromeOS have switched to Noto, and we strongly recommend everyone to replace Droid with Noto. Similarly, the Droid Sans Fallback font is superseded by Noto Sans CJK, available from noto-cjk.

**Comment by bohoomil** [comment]
Thanks for the info. You're right, in this case the package should be removed from the meta. I'll prepare the update once I'm back on Linux.
