### ISSUE TITLE
Last update (with freetype 2.7) made font rendering weird

### ISSUE THREAD

**Issue by volth** [bohoomil/fontconfig-ultimate#179]
Now it looks like this (Ubuntu Mono w/o anti-aliasing):

![screenshot_2016-09-15_10-55-15](https://cloud.githubusercontent.com/assets/508305/18547474/148dd894-7b33-11e6-84de-68dffc211304.png)

This is how it was with freetype 2.6.1 (I still have it a docker container and I am looking a way how to downgrade libfreetype on the laptop):

![screenshot_2016-09-15_11-03-55](https://cloud.githubusercontent.com/assets/508305/18547719/640d331e-7b34-11e6-94f3-829899bc02e0.png)

PS. github blurs the images so you have to click to see them undistorted

**Comment by onodera-punpun** [comment]
There are no (official) infinality patches for 2.7 yet...

**Comment by volth** [comment]
This, https://launchpad.net/~no1wantdthisname/+archive/ubuntu/ppa
Update from 13 Sep.
Not sure if it is the right bugtracker, they have it in readme.

**Comment by vooze** [comment]
volth: those packages are very different from these. I build them myself, to void using that PPA, since it seems to break alot.
