### ISSUE TITLE
Only font substitution

### ISSUE THREAD

**Issue by mattia-b89** [bohoomil/fontconfig-ultimate#183]
Sorry, maybe this is not the right place...

I switched back to *vanilla* freetype2 and _now_ it is not so bad
The only thing I miss from *infinality* are their font substitutions.
Is there any way to get it without all the *infinality* environment?

**Comment by rumpelsepp** [comment]
That is the reason that prevents me from dropping bohoomils stuff. The font substitutions and the font repo is just so beautiful... I have no idea. Maybe some time in the future there comes the point where we must create a separete project, where we can maintain the font substitution config. I personally would be fine to switch back to freetype 2.7 upstream without infinality patches and keep the fontconfig/fontpackages from here.

**Comment by jurf** [comment]
`fontconfig` has it's own metric-compatible font substitutions, you should be fine with just them.

**Comment by mattia-b89** [comment]
I'm with the bohoomill one because I vastly prefer it over the vanilla...

**Comment by gothmog123** [comment]
I'm in the same shoes... what is solution guys? Do we have to keep using and unmaintained fontconfig? How do the other distros do it?

**Comment by ubone** [comment]
https://github.com/bohoomil/fontconfig-ultimate/issues/191#issuecomment-289799221

**Comment by mattia-b89** [comment]
I want to close the issue, since I've finally found a proper and satisfying solution:
are now months that I use vanilla software {fontconfig, freetyp2, cairo} coupled with two AUR packages fonts-meta-base (https://aur.archlinux.org/packages/fonts-meta-base/) and fonts-meta-extended-lt (https://aur.archlinux.org/packages/fonts-meta-extended-lt/); I can state that new software version coupled with Bohoomil font substitutions provided by the two AUR packages, give me the same (good and smooth on my 24" LCD) graphical results as with Infinality-patched and Bohoomil stuff
