### ISSUE TITLE
multilib/wine Wine cannot find the FreeType font library.

### ISSUE THREAD

**Issue by winny-** [bohoomil/fontconfig-ultimate#190]
When I fired up my wine prefix today I saw `Wine cannot find the FreeType font library.` and no fonts in the wine applications. I then proceeded to try to build muiltilib/wine from ABS and I got this error: `configure: error: FreeType 64-bit development files not found. Fonts will not be built.`

I can verify the freetype2-infinality-ultimate package is installed correctly. `freetype-config --libs` works as well.

I'm not even certain if this is an issue with infinality. What else could I try?

**Comment by andrewfader** [comment]
I have this probably as well. Apparently the latest freetype has changes and infinality hasn't been maintained. See: https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671

**Comment by winny-** [comment]
Oops! I had followed that guide and hadn't update this issue. Closing.
