### ISSUE TITLE
would you like to provide a rsync server for bohoomil.com

### ISSUE THREAD

**Issue by zuyih** [bohoomil/fontconfig-ultimate#26]
I want to clone the mirrors,but wget is  inconvenient.

**Comment by KenetJervet** [comment]
For anyone that might be looking for bohoomil mirrors:
The mirror provided by @hzy199411 does not work any more.

**Comment by Firef0x** [comment]
Hi @KenetJervet ,

Sorry for late reply! The mirror provided by @hzy199411 has moved. See https://github.com/ustclug/mirrorrequest/issues/9#issuecomment-145006349 and https://lug.ustc.edu.cn/wiki/mirrors/help/infinality-bundle .

Appreciate USTC LUG!
Yours sincerely!
