### ISSUE TITLE
Add jre7-openjdk-headless-infinality to the repo

### ISSUE THREAD

**Issue by Bersam** [bohoomil/fontconfig-ultimate#35]
Hi,
I'm asking if you could, maintain this package and add this to your repository, cause rebuilding openjdk cost too much cpu usage and also need more than ~4.5 GB build space.
https://aur.archlinux.org/packages/jre7-openjdk-headless-infinality/
And here is a topic about this package and problem with official openjdk package:
https://bbs.archlinux.org/viewtopic.php?pid=1448519

**Comment by PGPereira** [comment]
Is there any way I can help? How do a repository work? I can build it and send it for you, if you want

**Comment by bohoomil** [comment]
@PGPereira Hello again and thanks a lot for offering assistance. Actually, I built jdk8-openjdk-infinality v. 8.u31-1 this weekend and now I'm going to test it. If everything looks fine, nothing breaks (including my nerves) and my CPU remains operational, I'll build the latest official release for both architectures and upload it when stock packages hit the `[extra]`. At the moment, this is going to be a test release of OpenJDK with Infinality: I've never used it before on a regular basis so there might be issues I'm not aware of. Anyway, we'll see what's it like. I'll appreciate your feedback if you decide to check it out on your machine. :-)

**Comment by bohoomil** [comment]
As `openjdk-infinality` is already in the repository, the thread can be closed.
