### ISSUE TITLE
Proposal: Standardize the using of `fc-cache` in install scripts

### ISSUE THREAD

**Issue by Firef0x** [bohoomil/fontconfig-ultimate#64]
Hello, @bohoomil ! :smiley: 

Appreciate your great work! I think we should standardize the using of `fc-cache` in all install scripts. It should be `fc-cache -s` . Currently I see:

```sh
fc-cache -f /path/to/fonts > /dev/null
fc-cache -sf > /dev/null
```

The reason to use `fc-cache -s` and some examples are as follow:

* [[arch-dev-public]fc-cache in install scriptlets](https://lists.archlinux.org/pipermail/arch-dev-public/2015-January/026889.html) and [reply](https://lists.archlinux.org/pipermail/arch-dev-public/2015-January/026890.html)
* [adobe-source-han-sans-fonts](https://projects.archlinux.org/svntogit/community.git/commit/trunk?h=packages/adobe-source-han-sans-fonts&id=77d7a1538c535762af38f3801bf243f0a0f35e2a)
* [ttf-droid](https://projects.archlinux.org/svntogit/community.git/commit/trunk?h=packages/ttf-droid&id=fc72bdf0259013224a23093f0eeba0fee17fd588)
* [ttf-ms-win8](http://pkgbuild.com/git/aur-mirror.git/diff/ttf-ms-win8/ttf-ms-win8.install?id=22c07276732384b77ada087dc560eb174d9c0cc9)
* [ttf-oxygen](https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/ttf-oxygen&id=5534277bc973ef03c8c163a1ba44b27dd778a0b5)
* [ttf-symbola](https://projects.archlinux.org/svntogit/community.git/commit/trunk?h=packages/ttf-symbola&id=4b789ee29fa3feeca6bc17fe20968b14850f6db3)
* [ttf-ubuntu-font-family](https://projects.archlinux.org/svntogit/community.git/commit/trunk?h=packages/ttf-ubuntu-font-family&id=ec256fc017410bed6ac0d0c482703e4a36dbe5ac)

Do you agree with me? Hope for your reply!

Happy new year! :gift:

**Comment by bohoomil** [comment]
Hello @Firef0x,

Take a look at #19, especially why `-sf` option is used in `post_remove` array.

Have a great new year, too! ;-)

**Comment by bohoomil** [comment]
@jristz Would you mind helping out with repackaging then? ;-) The only significant difference between our packages and the official is the `post_remove` snippet: installation and upgrade actually work in the same way, the difference is that we force creation of cache files only for the newly added/upgraded fonts. But OK, I will think about this one day.

FreeFonts is a no-go, though. It's old and terrible, and we don't really need that (Noto families provide us with even more glyphs and we have plenty of better options when special-purpose fonts are concerned: TeX Gyre Math extensions, Junicode, Symbola, etc.).

**Comment by jristz** [comment]
So what is better -sf por -s I can file bugs for allí on the todo in Arch
or clone and fix The postinstall here to -fs or -s. What to do?

**Comment by bohoomil** [comment]
The `-s` option should basically suffice: even if you remove the font manually from your collection without `pacman`, the cache file corresponding with it will be automatically removed. Sometimes however, things may go wrong and running `fc-cache -f(s)` is a good method to prevent the cache from getting cluttered with dead/invalid files. We decided to use the `-f` option after removing a package mainly for "hygienic" reasons: it just ensures that there are no leftovers/invalid cache files in your system that can mess around. For me the problem doesn't really exist because I run `fc-cache -f` manually every now and again (when you test new fonts it's a good idea to do this anyway). The problem is that this isn't a common practice for many users and then we can read "bad rendering" alerts on the Forums. :-)

As I've already written above, I'll think about reshaping the `install` scripts in the `ib-fonts` packages and let's leave the official Arch standards the way they are.

**Comment by jristz** [comment]
Well then I ask: Where are the post_install files to give a look?

**Comment by bohoomil** [comment]
Check out the [pkgbuild](https://github.com/bohoomil/fontconfig-ultimate/tree/pkgbuild) branch: there's one `*.install` file in every font package.

**Comment by jristz** [comment]
Ok I leave the pkgrel intact or you want update all the packages too?

**Comment by Firef0x** [comment]
Hello, @bohoomil ! :smiley:

It took me a long time to finish reading and understanding Issue #19 #64 and #67 . And I convince you are a **font expert**! I think you have clarified the pros and cons of argument `-f`, clearer than what Allan McRae said in the mailing list. Hope that the TUs could take a look here and join you in making the [Font package guideline](https://wiki.archlinux.org/index.php/Arch_packaging_standards#Additional_guidelines).

Now that I have no reason to persuade you to follow the Arch official, could this issue be an broad discussion about font package guideline? Or I just close it?

Yours sincerely! :bow:

**Comment by bohoomil** [comment]
@Firef0x! Kill it with fire! ;-)

I think we're done with packaging standards for good (or at least for some time). Let's just stick with what we have: the only thing the users should remember is `fc-cache -f(s)` command they may want to run from time to time, especially when out of the sudden they experience issues with fonts not loading/displaying glyphs properly. Otherwise, we should be happy with the change.

Thanks and good luck!

**Comment by Firef0x** [comment]
Hello, @bohoomil !

OK, I'll close it! :negative_squared_cross_mark: I didn't notice that you have updated the install scripts of all font packages, and I am curious about the consideration you chose to follow the official Arch ones finally. As you said:

> installation and upgrade actually work in the same way.
> `-f` ensures that there are no leftovers/invalid cache files in your system that can mess around.

I'd like to learn the lesson from this issue.

Yours sincerely!

**Comment by jristz** [comment]
I've added you to the family tree on Geni, a website that helps families create and share their family tree and stay in touch with each other.


http://www.geni.com/c/87df7948aac8a097aa0982cae98a123626c04476





Kind regards,

- The Geni Team




------------------------------------------------------------
You are currently signed up to be notified of request activity. Unsubscribe: http://www.geni.com/account_settings/unsubscribe_confirm?e=reply%2B000d0eae954b917a99c34f9e4efe82944bd40b613d51aeef92cf0000000110c461ab92a169ce032f34aa%40reply.github.com&h=1528768762a95f727f650bd739087bf8&l=87df7948aac8a097aa0982cae98a123626c04476&email_type=follow_request

(c) Geni.com | P.O. Box 4015, Burbank, CA 91503 USA

**Comment by flamusdiu** [comment]
@jristz I think something happen to this thread.

**Comment by bohoomil** [comment]
@flamusdiu 'Something' in this case we call spam...

**Comment by flamusdiu** [comment]
@bohoomil haha. I know. I was just pointing it out (probably didn't need to). =P

**Comment by jristz** [comment]
I've added you to the family tree on Geni, a website that helps families create and share their family tree and stay in touch with each other.


http://www.geni.com/c/8153842ab40bb6d625b6dbd78b7be89175febed9





Kind regards,

- The Geni Team




------------------------------------------------------------
You are currently signed up to be notified of request activity. Unsubscribe: http://www.geni.com/account_settings/unsubscribe_confirm?e=reply%2B000d0eae954b917a99c34f9e4efe82944bd40b613d51aeef92cf0000000110c461ab92a169ce032f34aa%40reply.github.com&h=1528768762a95f727f650bd739087bf8&l=8153842ab40bb6d625b6dbd78b7be89175febed9&email_type=follow_request

(c) Geni.com | P.O. Box 4015, Burbank, CA 91503 USA

**Comment by Firef0x** [comment]
@flamusdiu What are you talking about? No clues. :confused:
