### ISSUE TITLE
Issue with a single font in Thunderbird message

### ISSUE THREAD

**Issue by orschiro** [bohoomil/fontconfig-ultimate#72]
Dear @bohoomil,

I encounter a very specific issue with an email sent by a particular contact. I don't know from where to get more information about the particular font in use. The email message looks as follows:

![image](https://cloud.githubusercontent.com/assets/170947/6009951/005263e8-ab2f-11e4-8228-5b82f6039a39.png)

For me personally, the email font is very inconvenient to read due to its narrow letter spacing. 

What might I be doing with it?

```
cairo-infinality-ultimate 1.14.0-2
fontconfig-infinality-ultimate 2.11.1-24
freetype2-infinality-ultimate 2.5.5-2
lib32-cairo-infinality-ultimate 1.14.0-2
lib32-fontconfig-infinality-ultimate 2.11.1-3
lib32-freetype2-infinality-ultimate 2.5.5-2
```

```
❯ fc-presets check
 [ combi ] is not set 
 :: Run <fc-presets help> for more information.

 5 symlinks found.
 The active preset seems to be [ free ].
 Checking symlinks now...

30-metric-aliases-free.conf is OK
37-repl-global-free.conf is OK
60-latin-free.conf is OK
65-non-latin-free.conf is OK
66-aliases-wine-free.conf is OK
```

Thankfully,

Robert

**Comment by bohoomil** [comment]
Hello Robert,

Did you try changing the font in `Preferences -> Display -> Formatting -> Advanced -> Western => <your_fonts>`? You can do the same with other language scripts.

**Comment by orschiro** [comment]
Yes, I did:

![image](https://cloud.githubusercontent.com/assets/170947/6016323/648f14e0-ab80-11e4-8921-adcd6080ab83.png)

I could force all messages to use that font (uncheck `Allow messages to use other fonts`) but then I am losing a lot of proper formatting of HTML mails.

**Comment by bohoomil** [comment]
Nope, I didn't mean unchecking this option... Simply tell your pen-pal to change the font. ;-)

What I think we can try doing anyway: display the message as a source code and check which font it actually is. Then we can set a replacement rule for it.

**Comment by orschiro** [comment]
Found it!

```
 <body bgcolor="#FFFFFF" text="#000000">
    <font face="Arial Narrow">Hallo Robert,<br>
      <br>
```

**Comment by bohoomil** [comment]
Thanks. The default substitution for Arial Narrow in the free preset is this (`37-repl-global-free.conf`):

```xml
  <!-- Arial Narrow => Liberation Sans Narrow -->
  <match target="font">
    <test name="family">
      <string>Arial Narrow</string>
    </test>
    <edit name="family" mode="assign">
      <string>Liberation Sans Narrow</string>
    </edit>
  </match>
  <match target="pattern">
    <test name="family">
      <string>Arial Narrow</string>
    </test>
    <edit name="family" mode="prepend" binding="strong" >
      <string>Liberation Sans Narrow</string>
    </edit>
  </match>
```

Now simply copy the snippet, paste it to `35-repl-custom.conf` and change Liberation Sans Narrow to anything you wish (you can simply stick with Liberation Sans).

By the way, the problem isn't really your settings, but hers -- she should set a proper font for the body text, and the one shouldn't be narrow...

**Comment by orschiro** [comment]
@bohoomil 

Thank you for the snippet! 

> By the way, the problem isn't really your settings, but hers -- she should set a proper font for the body text, and the one shouldn't be narrow...

I will let her know subtly. ;)
