### ISSUE TITLE
pacman-key -r 962DDE58 IPC connect call failed

### ISSUE THREAD

**Issue by fastrizwaan** [bohoomil/fontconfig-ultimate#73]
In antergos, i'm unable to install the key. Please guide.
root@antergos-pc rizvan]# pacman-key -r 962DDE58
gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: IPC connect call failed

pacman.conf:
[infinality-bundle]
Server = http://bohoomil.com/repo/$arch

[infinality-bundle-fonts]
Server = http://bohoomil.com/repo/fonts

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[community-testing]
#Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

**Comment by bohoomil** [comment]
See this one [2014-12-23 11:13:14](https://bbs.archlinux.org/viewtopic.php?pid=1486862#p1486862) and the following posts.

**Comment by fastrizwaan** [comment]
Thanks, got it working by changing SigLevel to Never and The time was messed up.
