### ISSUE TITLE
Conky fonts look to small

### ISSUE THREAD

**Issue by PGPereira** [bohoomil/fontconfig-ultimate#78]
First of all, I really apreciate your project, bohoomil.

Today I installed conky, but it's fonts are looking too small. In the arch wiki I was told to change from 72 to 96 DPI in tha file  /etc/fonts/infinality/infinality.conf, but my system doesn't have it. Where do I find this file?

**Comment by bohoomil** [comment]
There isn't and has never been anything like `/etc/fonts/infinality/infinality.conf`. We do have, however, `/etc/fonts/fonts.conf`, but the extra, non-standard DPI entry will be removed from it on the next update (it's deprecated and not needed for anything any longer).

DPI shouldn't be used to manipulate font size. If your conky fonts look too small, you should simply increase the size using appropriate parameters the application provides.

**Comment by PGPereira** [comment]
Should I change this in the arch wiki then?

**Comment by bohoomil** [comment]
I don't control the Infinality article in any way so, well, it's really up to you. ;-)
