### ISSUE TITLE
jdk8-openjdk-infinality not working as it should

### ISSUE THREAD

**Issue by PGPereira** [bohoomil/fontconfig-ultimate#79]
I've installed the jdk8 from your repo and it appears to be not working, because with it configured in archlinux-java  netbeans stopped working (it works ok with the openjdk from default repos, or the oracle java), but I can't confirm, since netbeans is the only java application I have.

**Comment by bohoomil** [comment]
Did you remove the stock openjdk first as suggested [here](https://bbs.archlinux.org/viewtopic.php?pid=1510244#p1510244)?

**Comment by PGPereira** [comment]
Yes. I had found a solution: remove the netbeans cache from my PC, now it works well.

**Comment by bohoomil** [comment]
Great!
