### ISSUE TITLE
Fira fonts 4

### ISSUE THREAD

**Issue by cocreature** [bohoomil/fontconfig-ultimate#80]
Not sure if there is a better place to report this, but the fira mons have been released in version 4 (community repos are already updated). Would be great if you could update the packages for them.

**Comment by bohoomil** [comment]
Sure, thanks for the info. I'll prepare the package soon.

**Comment by bohoomil** [comment]
Done. BTW, only Fira Sans was upgraded to 4.004 (as of 2015-03-19), Mono is still 3.111.

**Comment by cocreature** [comment]
Great, thanks for the quick response (and also thanks for all the work you are putting into this font stuff, you're awesome). I'll wait for mono (take your time :)).

**Comment by bohoomil** [comment]
There is no 4.003/4.004 Mono available. In `[community]`, only the package versions were changed, Mono fonts are still 3.111. ;-)

**Comment by cocreature** [comment]
Oh allright, closing this then.
