### ISSUE TITLE
Bug: doublecmd-gtk2 fails at start with "Division by Zero"

### ISSUE THREAD

**Issue by Firef0x** [bohoomil/fontconfig-ultimate#81]
Hello @bohoomil ,

Description
---
After last system update, 'doublecmd-gtk2' fails at start with `Division by Zero`:

```sh
(doublecmd:4661): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[FORMS.PP] ExceptionOccurred 
  Sender=EDivByZero
  Exception=Division by zero
  Stack trace:
  $00007FF7B112A03A
TApplication.HandleException Division by zero
  Stack trace:
  $00007FF7B112A03A
[FORMS.PP] ExceptionOccurred 
```

Workaround
---
As is mentioned in https://bugs.archlinux.org/task/44251#comment133611 , rolling back from `fontconfig-infinality-ultimate` 2.11.1-26 to `fontconfig-infinality-ultimate` 2.11.1-24 makes doublecmd-gtk starts again!

Is it a bug of `fontconfig-infinality-ultimate` ? Hope for your reply! :grinning: 

Yours sincerely!

**Comment by bohoomil** [comment]
I'll just leave it here…

https://bbs.archlinux.org/viewtopic.php?pid=1512661#p1512661

**Comment by Firef0x** [comment]
Sorry that I neglected it. Feel free to close this issue, or wait till the fontconfig devs fixed the bug.

**Comment by bohoomil** [comment]
;-)
