### ISSUE TITLE
'/etc/X11/xinit/xinitrc.d/infinality-settings' should have '.sh' suffix.

### ISSUE THREAD

**Issue by dontdieych** [bohoomil/fontconfig-ultimate#85]
See this bug report.

https://bugs.archlinux.org/task/41471

I start X using `startx` command on console. So I copied '/etc/X11/xinit/xinitrc' to '$HOME/.xinitrc' then edit it.

```
if [ -d /etc/X11/xinit/xinitrc.d ] ; then                                        
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do                                       
  [ -x "$f" ] && . "$f"                                                          
 done                                                                            
 unset f                                                                         
fi                                                                               
```

Because this block, infinalty settings does not applied.

**Comment by bohoomil** [comment]
When you use a simple wildcard (`*` without a suffix) everything should work and I'd recommend you leave it this way. However, I can suffix the file as well if it makes it more robust.

I will introduce the change on the next update.

**Comment by dontdieych** [comment]
Thanks. Your are my hero.

**Comment by dontdieych** [comment]
Thanks.
2015. 4. 27. 오전 6:34에 "bohoomil" <notifications@github.com>님이 작성:

**Comment by bohoomil** [comment]
My pleasure. :-)
