### ISSUE TITLE
conf.avail.infinality/83-yes-bitmaps.conf bool value should be false?

### ISSUE THREAD

**Issue by fungible** [bohoomil/fontconfig-ultimate#86]
In conf.avail.infinality/83-yes-bitmaps.conf, I think the bool value should be false, as it should follow with the conf.avail.infinality/82-no-bitmaps.conf template. Also the default fontconfig template 70-yes-bitmaps.conf also shows false bool value.

**Comment by bohoomil** [comment]
Good point: will be fixed soon.

Thanks a lot for reporting.
