### ISSUE TITLE
Strange 'fi' ligature in latin text 

### ISSUE THREAD

**Issue by szymonszydelko** [bohoomil/fontconfig-ultimate#93]
Please look at the picture. This surfaced after the last pacman update I've did.

![selection_017](https://cloud.githubusercontent.com/assets/3144357/7690638/a7a975d6-fdb5-11e4-8419-36a331d3db13.png)

The browser is Firefox, also, other ligatures have started appearing, like 'fl'.

**Comment by bohoomil** [comment]
Try cleaning the cookies and rebuilding the font cache in the first place. With so little data provided, I'm not able to reproduce the problem: generic reddit renders correctly to me.

**Comment by szymonszydelko** [comment]
OK, clearing the font cache helped. Not sure what caused the problem, though.
