### ISSUE TITLE
Freetype 2.6 support

### ISSUE THREAD

**Issue by thypon** [bohoomil/fontconfig-ultimate#95]
The patches can't be applied to freetype 2.6.

**Comment by bohoomil** [comment]
Which "patches"? Do you happen to read the output of your patching application, compiler, etc.? Some basic investigation before filing a bug report? :-p

**Comment by thypon** [comment]
I "mantain" the patchset for https://github.com/voidlinux/void-packages. Right now only the upstream patch doesn't apply, but was quite expected. The other two applies with hunks.

**Comment by bohoomil** [comment]
There's actually one hunk:

```
patching file src/truetype/ttinterp.c
Hunk #1 succeeded at 5811 (offset 25 lines).
```

It's purely cosmetic, hence the patch is still successfully applied (I'll update it one day, though). The upstream patch is always made redundant as soon as the new official major/minor version is released. If this is "expected" (obviously) so what's the big deal?

**Comment by thypon** [comment]
Nothing. :+1: for the hard work. Was more of a reminder.
