### ISSUE TITLE
infinality patch no longer applies to freetype 2.6

### ISSUE THREAD

**Issue by ismail** [bohoomil/fontconfig-ultimate#96]
Hi, getting some rejects:

     + /usr/bin/cat /home/abuild/rpmbuild/SOURCES/03-infinality-2.6-2015.06.08.patch
     + /usr/bin/patch -p1 --fuzz=0
     patching file configure
     patching file devel/ftoption.h
     Hunk #1 succeeded at 609 (offset 2 lines).
     patching file include/config/ftoption.h
     Hunk #2 succeeded at 604 (offset 2 lines).
     patching file src/autofit/aflatin.c
     Hunk #3 succeeded at 897 (offset -1 lines).
     Hunk #4 succeeded at 950 (offset -1 lines).
     Hunk #5 succeeded at 960 (offset -1 lines).
     Hunk #6 succeeded at 1084 (offset -1 lines).
     Hunk #7 succeeded at 1141 (offset -1 lines).
     Hunk #8 succeeded at 1959 (offset -1 lines).
     Hunk #9 succeeded at 2128 (offset -10 lines).
     Hunk #10 succeeded at 2162 (offset -10 lines).
     Hunk #11 succeeded at 2288 (offset -10 lines).
     Hunk #12 succeeded at 2298 (offset -10 lines).
     Hunk #13 succeeded at 2364 (offset -10 lines).
     Hunk #14 FAILED at 2421.
     Hunk #15 succeeded at 2975 (offset -6 lines).
     Hunk #16 succeeded at 3066 (offset -8 lines).
     1 out of 16 hunks FAILED -- saving rejects to file src/autofit/aflatin.c.rej
     patching file src/autofit/aflatin.h
     Hunk #1 FAILED at 62.
     1 out of 1 hunk FAILED -- saving rejects to file src/autofit/aflatin.h.rej
     patching file src/base/ftlcdfil.c
     patching file src/base/ftobjs.c
     patching file src/base/ftoutln.c
     Hunk #1 succeeded at 917 (offset 7 lines).
     patching file src/base/ftsynth.c
     patching file src/smooth/ftsmooth.c
     Hunk #6 FAILED at 3793.
     1 out of 10 hunks FAILED -- saving rejects to file src/smooth/ftsmooth.c.rej
     patching file src/truetype/ttinterp.c
     Hunk #1 FAILED at 5811.
     1 out of 1 hunk FAILED -- saving rejects to file src/truetype/ttinterp.c.rej

**Comment by bohoomil** [comment]
https://github.com/bohoomil/fontconfig-ultimate/issues/95

**Comment by ismail** [comment]
Well you see this is not a duplicate of #95 , I don't apply the upstream patch at all. As you see 03-infinality-2.6-2015.06.08.patch itself fails.

**Comment by ismail** [comment]
Never mind, patch fails with --fuzz=0 , needs a refresh.

**Comment by bohoomil** [comment]
Yes, it somehow is a duplicate of #95. The patch applies fine to the **clean 2.6 code base**. If it fails for you, than you must be doing something wrong. Are you first patching the code with some distro-exclusive bits, for instance? Did you try changing patch options, e.g. use '-Np1 -i' instead of '--fuzz=0'? Check this out, please.

**Comment by ismail** [comment]
Yep you are right, patches apply cleanly on top of vanilla freetype, sorry for the noise! And thanks for your hard work.
